modLoader="javafml" 
loaderVersion="[34,)"
license="GPL3"
issueTrackerURL="https://github.com/MrCrayfish/Catalogue/issues"

[[mods]]
modId="catalogue"
version="1.2.2"
displayName="Catalogue"
authors="MrCrayfish"
logoFile="catalogue.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/catalogue"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=catalogue"
description="Updates Forge's mod list with a new and improved design"
credits="Hatsondogs for creating icons"

[[dependencies.catalogue]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.catalogue]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"

[modproperties.catalogue]
    catalogueImageIcon="catalogue.png"
